#!/bin/bash

echo "Creating directory structure"
mkdir -p src/components
mkdir -p src/containers
mkdir -p src/reducers
touch src/reducers/index.js
mkdir -p src/actions
mkdir -p src/app_descriptor
cat > src/app_descriptor/app.js << EOF
import { Route } from 'react-router';
export default {
    // Export here the main reducer of you app
    reducer: () => 0,
    // Here export your routes
    routes: <Route path="/" />,
};
EOF
# Todo ask if export eslint
cat >.eslintrc << EOF
{
    "extends": "./node_modules/fondation/.eslintrc"
}
EOF
cat >.gitignore << EOF
/node_modules/
/public/bundle.js
/public/bundle.js.map
/build/
EOF
cat > src/client.js << EOF
import { bootstrapClient } from 'fondation';

bootstrapClient();
EOF

# Installing peer dependencies :(
echo "Installing peer dependencies"
npm install history react react-dom react-router jsonwebtoken koa koa-bodyparser koa-jwt koa-router koa-static koa-validate redux react-redux redux-simple-router redux-thunk superagent isomorphic-style-loader
echo "Linking to fondation"
npm link fondation


