#!/bin/bash

npm init
mkdir -p src/components
mkdir -p src/containers
mkdir -p src/reducers
mkdir -p src/appDescriptor
cat > src/appDescriptor/app.js << EOF
import { Route } from 'react-router';
export default {
    // Export here the main reducer of you app
    reducer: () => 0,
    // Here export your routes
    routes: <Route path="/" />,
};
EOF
# Todo ask if export eslint
cat >.eslintrc << EOF
{
    "extends": "./node_modules/fondation/.eslintrc"
}
EOF

cat >.gitignore << EOF
/node_modules/
/public/bundle.js
/public/bundle.js.map
/build/
EOF
cat > src/client.js << EOF
import { bootstrapClient } from 'fondation';

bootstrapClient();
EOF

npm install redux react react-router redux react-redux react-dom
npm link fondation

echo "### Fondation project successfully initialized, starting hot server ###"
./node_modules/fondation/bin/fondation serve-hot

