#!/bin/bash
bin=$FONDATION_PATH/node_modules/.bin
build_config=$FONDATION_PATH/src/build_config/webpack.config.server.es5.js

$bin/webpack --progress --env.dev --env.hot --config $build_config && \

$bin/parallelshell "node ./build/server.js" \
"$bin/webpack --env.dev --env.hot --watch --config $build_config > /dev/null"
